apiVersion: v1
kind: Service
metadata:
  name: market-data-streamer
  labels:
    app: market-data-streamer
    service: market-data-streamer
spec:
  ports:
    - port: 7171
      name: http
    - port: 57171
      name: grpc
  selector:
    app: market-data-streamer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptoofun-market-data-streamer
  labels:
    account: market-data-streamer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-streamer-v1
  labels:
    app: market-data-streamer
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: market-data-streamer
      version: v1
  template:
    metadata:
      labels:
        app: market-data-streamer
        version: v1
    spec:
      serviceAccountName: cryptoofun-market-data-streamer
      containers:
        - name: market-data-streamer
          image: gcr.io/cryptoofun/market-data-streamer:1.0.0
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis-release-master.redis.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: password
            - name: BINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-secrets
                  key: api-key
            - name: BINANCE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-secrets
                  key: secret-key
          ports:
            - name: http
              protocol: TCP
              containerPort: 7171
              hostPort: 7171
            - name: grpc
              protocol: TCP
              containerPort: 57171
              hostPort: 57171
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
