apiVersion: v1
kind: Service
metadata:
  name: order-processor
  labels:
    app: order-processor
    service: order-processor
spec:
  ports:
    - port: 1
  selector:
    app: order-processor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptoofun-order-processor
  labels:
    account: order-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor-v1
  labels:
    app: order-processor
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-processor
      version: v1
  template:
    metadata:
      labels:
        app: order-processor
        version: v1
    spec:
      serviceAccountName: cryptoofun-order-processor
      containers:
        - name: order-processor
          image: gcr.io/cryptoofun/order-processor:1.0.0
          imagePullPolicy: Always
          env:
            - name: GRPC_SV_CASH_WALLET
              value: static://cash-wallet.cf.svc.cluster.local:57370
            - name: GRPC_SV_MARKET_DATA
              value: static://market-data-streamer.cf.svc.cluster.local:57171
            - name: GRPC_SV_PORTFOLIO
              value: static://portfolio.cf.svc.cluster.local:57371
            - name: KAFKA_BS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: bootstrap-servers
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: sasl-mechanism
            - name: KAFKA_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: cfg-with-secrets
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
