apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    app: portfolio
    service: portfolio
spec:
  ports:
    - port: 7371
      name: http
    - port: 57371
      name: grpc
  selector:
    app: portfolio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptoofun-portfolio
  labels:
    account: portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-v1
  labels:
    app: portfolio
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
      version: v1
  template:
    metadata:
      labels:
        app: portfolio
        version: v1
    spec:
      serviceAccountName: cryptoofun-portfolio
      containers:
        - name: portfolio
          image: gcr.io/cryptoofun/portfolio:1.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "7371"
            - name: GRPC_SERVER_PORT
              value: "57371"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: crdb-secrets
                  key: portfoliodb_conn_str
          ports:
            - name: http
              protocol: TCP
              containerPort: 7371
              hostPort: 7371
            - name: grpc
              protocol: TCP
              containerPort: 57371
              hostPort: 57371
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
