apiVersion: v1
kind: Service
metadata:
  name: profile
  labels:
    app: profile
    service: profile
spec:
  ports:
    - port: 57372
      name: grpc
  selector:
    app: profile
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptoofun-profile
  labels:
    account: profile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-v1
  labels:
    app: profile
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
      version: v1
  template:
    metadata:
      labels:
        app: profile
        version: v1
    spec:
      serviceAccountName: cryptoofun-profile
      containers:
        - name: profile
          image: gcr.io/cryptoofun/profile:1.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: GRPC_SERVER_PORT
              value: "57372"
            - name: AUTH0_DOMAIN
              value: cryptoofun.eu.auth0.com
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-management-secrets
                  key: client_id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-management-secrets
                  key: client_secret
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 57372
              hostPort: 57372
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
