apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    service: webapp
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptoofun-webapp
  labels:
    account: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      serviceAccountName: cryptoofun-webapp
      containers:
        - name: webapp
          image: gcr.io/cryptoofun/webapp:1.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: PORT
              value: "3000"
            - name: API_ROOT_DOMAIN
              value: cf.svc.cluster.local
            - name: AUTH0_BASE_URL
              value: "" # ! Override at runtime (self domain and/or IP address)
            - name: AUTH0_ISSUER_BASE_URL
              value: https://cryptoofun.eu.auth0.com
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: rand_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: client_id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: client_secret
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
              hostPort: 80
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
