apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    service: webapp
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptoofun-webapp
  labels:
    account: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      serviceAccountName: cryptoofun-webapp
      containers:
        - name: webapp
          image: gcr.io/cryptoofun/webapp:1.0.0
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: PORT
              value: "3000"
            - name: API_ROOT_DOMAIN
              value: cf.svc.cluster.local
            - name: API_TRADEBUTLER_BASE_URL
              value: http://trade-butler.cf.svc.cluster.local:7170
            - name: API_MARKETDATASTREAMER_BASE_URL
              value: http://market-data-streamer.cf.svc.cluster.local:7171
            - name: API_LEADERBOARD_BASE_URL
              value: http://leaderboard.cf.svc.cluster.local:7372
            - name: API_CASHWALLET_BASE_URL
              value: http://cash-wallet.cf.svc.cluster.local:7370
            - name: API_PORTFOLIO_BASE_URL
              value: http://portfolio.cf.svc.cluster.local:7371
            - name: API_LOBBY_BASE_URL
              value: http://lobby.cf.svc.cluster.local:7373
            - name: API_PROGRESSION_BASE_URL
              value: http://progression.cf.svc.cluster.local:7172
            - name: AUTH0_BASE_URL
              value: "" # ! Override at runtime (represents external domain and/or IP address of the cluster). See k8s/exec_after_deploy.[ps1,sh] script.
            - name: AUTH0_ISSUER_BASE_URL
              value: https://cryptoofun.eu.auth0.com
            - name: AUTH0_AUDIENCE
              value: https://api.cryptoofun
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: rand_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: client_id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: client_secret
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
              hostPort: 80
          volumeMounts:
            - mountPath: /app/.next/cache
              name: cache
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
      volumes:
        - emptyDir: {}
          name: cache
