server:
  port: 7172

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BS}
    consumer:
      group-id: progression
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 45000
    properties:
      security:
        protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
      sasl:
        mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
        jaas:
          config: ${KAFKA_JAAS_CONFIG}

  data.cassandra:
    cloudConnectBundleUrl: ${CASSANDRA_CONNECT_BUNDLE_URL}
    keyspace: progression
    username: ${CASSANDRA_USERNAME:cassandra}
    password: ${CASSANDRA_PASSWORD:cassandra}
    schema-action: CREATE_IF_NOT_EXISTS
