apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "auth0"
  namespace: cf
spec:
  jwtRules:
    - issuer: "https://cryptoofun.eu.auth0.com/"
      jwksUri: "https://cryptoofun.eu.auth0.com/.well-known/jwks.json"
