grpc:
  server:
    port: -1
  client:
    cash-wallet-server:
      address: ${GRPC_SV_CASH_WALLET:static://0.0.0.0:50051}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    market-data-server:
      address: ${GRPC_SV_MARKET_DATA:static://0.0.0.0:57172}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    portfolio-server:
      address: ${GRPC_SV_PORTFOLIO:static://localhost:50052}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BS}
    consumer:
      group-id: order-processors
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 45000
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: ${KAFKA_JAAS_CONFIG}
