server:
  port: 7171

grpc:
  server:
    port: -1
  client:
    cash-wallet-server:
      address: 'static://0.0.0.0:9090' # TODO: Update ...
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext  # TODO: Switch to TLS in production
    market-data-server:
      address: 'static://0.0.0.0:9091' # TODO: Update ...
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext # TODO: Switch to TLS in production
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:127.0.0.1:19092}
    consumer:
      group-id: order-processors
      auto-offset-reset: earliest
