server:
  address: 0.0.0.0
  port: 7170

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BS}
    groupId: trade-butlers
    consumer:
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 45000
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: ${KAFKA_JAAS_CONFIG}

  data.cassandra:
    cloudConnectBundleUrl: ${CASSANDRA_CONNECT_BUNDLE_URL}
    keyspace: tradebutler
    username: ${CASSANDRA_USERNAME:cassandra}
    password: ${CASSANDRA_PASSWORD:cassandra}
    schema-action: CREATE_IF_NOT_EXISTS
