server:
  port: 7170

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:19092
    groupId: trade-butlers

  data.cassandra:
    contact-points: localhost
    port: 9042
    keyspace: tradebutler
    username: cassandra
    password: cassandra
    schema-action: CREATE_IF_NOT_EXISTS
