server:
  address: 0.0.0.0
  port: 7170

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BS}
    groupId: trade-butlers
    consumer:
      properties:
        session.timeout.ms: 45000
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: ${KAFKA_JAAS_CONFIG}
      # Schema Registry configs [DISABLED] ==>
      # basic.auth.credentials.source: USER_INFO
      # basic.auth.user.info: { { SR_API_KEY } }:{{ SR_API_SECRET }}
      # schema.registry.url: https://{{ SR_ENDPOINT }}

  data.cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT}
    keyspace: tradebutler
    username: ${CASSANDRA_USERNAME}
    password: ${CASSANDRA_PASSWORD}
    schema-action: CREATE_IF_NOT_EXISTS
