apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: portfolio-policy
  namespace: cf
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: portfolio
  rules:
    - when:
        - key: request.auth.claims[permissions]
          values: ["read:services", "write:services"]
    - to:
        - operation:
            methods: ["POST"]
            paths: ["/PortfolioService/*"]
