// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cash_wallet.proto

package io.github.cryptoofun.genproto;

public interface AskCashBalancesByOffsetAndLimitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskCashBalancesByOffsetAndLimitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  java.util.List<io.github.cryptoofun.genproto.BalanceItem> 
      getBalancesList();
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  io.github.cryptoofun.genproto.BalanceItem getBalances(int index);
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  int getBalancesCount();
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  java.util.List<? extends io.github.cryptoofun.genproto.BalanceItemOrBuilder> 
      getBalancesOrBuilderList();
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  io.github.cryptoofun.genproto.BalanceItemOrBuilder getBalancesOrBuilder(
      int index);
}
