// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cash_wallet.proto

package io.github.cryptoofun.genproto;

/**
 * Protobuf type {@code AskCashBalancesByOffsetAndLimitResponse}
 */
public final class AskCashBalancesByOffsetAndLimitResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AskCashBalancesByOffsetAndLimitResponse)
    AskCashBalancesByOffsetAndLimitResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AskCashBalancesByOffsetAndLimitResponse.newBuilder() to construct.
  private AskCashBalancesByOffsetAndLimitResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AskCashBalancesByOffsetAndLimitResponse() {
    balances_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AskCashBalancesByOffsetAndLimitResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.cryptoofun.genproto.CashWallet.internal_static_AskCashBalancesByOffsetAndLimitResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.cryptoofun.genproto.CashWallet.internal_static_AskCashBalancesByOffsetAndLimitResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse.class, io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse.Builder.class);
  }

  public static final int BALANCES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.github.cryptoofun.genproto.BalanceItem> balances_;
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  @java.lang.Override
  public java.util.List<io.github.cryptoofun.genproto.BalanceItem> getBalancesList() {
    return balances_;
  }
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.cryptoofun.genproto.BalanceItemOrBuilder> 
      getBalancesOrBuilderList() {
    return balances_;
  }
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  @java.lang.Override
  public int getBalancesCount() {
    return balances_.size();
  }
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  @java.lang.Override
  public io.github.cryptoofun.genproto.BalanceItem getBalances(int index) {
    return balances_.get(index);
  }
  /**
   * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
   */
  @java.lang.Override
  public io.github.cryptoofun.genproto.BalanceItemOrBuilder getBalancesOrBuilder(
      int index) {
    return balances_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < balances_.size(); i++) {
      output.writeMessage(1, balances_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < balances_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, balances_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse)) {
      return super.equals(obj);
    }
    io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse other = (io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse) obj;

    if (!getBalancesList()
        .equals(other.getBalancesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBalancesCount() > 0) {
      hash = (37 * hash) + BALANCES_FIELD_NUMBER;
      hash = (53 * hash) + getBalancesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AskCashBalancesByOffsetAndLimitResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AskCashBalancesByOffsetAndLimitResponse)
      io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.cryptoofun.genproto.CashWallet.internal_static_AskCashBalancesByOffsetAndLimitResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.cryptoofun.genproto.CashWallet.internal_static_AskCashBalancesByOffsetAndLimitResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse.class, io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse.Builder.class);
    }

    // Construct using io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (balancesBuilder_ == null) {
        balances_ = java.util.Collections.emptyList();
      } else {
        balances_ = null;
        balancesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.cryptoofun.genproto.CashWallet.internal_static_AskCashBalancesByOffsetAndLimitResponse_descriptor;
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse getDefaultInstanceForType() {
      return io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse build() {
      io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse buildPartial() {
      io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse result = new io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse result) {
      if (balancesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          balances_ = java.util.Collections.unmodifiableList(balances_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.balances_ = balances_;
      } else {
        result.balances_ = balancesBuilder_.build();
      }
    }

    private void buildPartial0(io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse) {
        return mergeFrom((io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse other) {
      if (other == io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse.getDefaultInstance()) return this;
      if (balancesBuilder_ == null) {
        if (!other.balances_.isEmpty()) {
          if (balances_.isEmpty()) {
            balances_ = other.balances_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBalancesIsMutable();
            balances_.addAll(other.balances_);
          }
          onChanged();
        }
      } else {
        if (!other.balances_.isEmpty()) {
          if (balancesBuilder_.isEmpty()) {
            balancesBuilder_.dispose();
            balancesBuilder_ = null;
            balances_ = other.balances_;
            bitField0_ = (bitField0_ & ~0x00000001);
            balancesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBalancesFieldBuilder() : null;
          } else {
            balancesBuilder_.addAllMessages(other.balances_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.cryptoofun.genproto.BalanceItem m =
                  input.readMessage(
                      io.github.cryptoofun.genproto.BalanceItem.parser(),
                      extensionRegistry);
              if (balancesBuilder_ == null) {
                ensureBalancesIsMutable();
                balances_.add(m);
              } else {
                balancesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.cryptoofun.genproto.BalanceItem> balances_ =
      java.util.Collections.emptyList();
    private void ensureBalancesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        balances_ = new java.util.ArrayList<io.github.cryptoofun.genproto.BalanceItem>(balances_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.cryptoofun.genproto.BalanceItem, io.github.cryptoofun.genproto.BalanceItem.Builder, io.github.cryptoofun.genproto.BalanceItemOrBuilder> balancesBuilder_;

    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public java.util.List<io.github.cryptoofun.genproto.BalanceItem> getBalancesList() {
      if (balancesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(balances_);
      } else {
        return balancesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public int getBalancesCount() {
      if (balancesBuilder_ == null) {
        return balances_.size();
      } else {
        return balancesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public io.github.cryptoofun.genproto.BalanceItem getBalances(int index) {
      if (balancesBuilder_ == null) {
        return balances_.get(index);
      } else {
        return balancesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder setBalances(
        int index, io.github.cryptoofun.genproto.BalanceItem value) {
      if (balancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBalancesIsMutable();
        balances_.set(index, value);
        onChanged();
      } else {
        balancesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder setBalances(
        int index, io.github.cryptoofun.genproto.BalanceItem.Builder builderForValue) {
      if (balancesBuilder_ == null) {
        ensureBalancesIsMutable();
        balances_.set(index, builderForValue.build());
        onChanged();
      } else {
        balancesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder addBalances(io.github.cryptoofun.genproto.BalanceItem value) {
      if (balancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBalancesIsMutable();
        balances_.add(value);
        onChanged();
      } else {
        balancesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder addBalances(
        int index, io.github.cryptoofun.genproto.BalanceItem value) {
      if (balancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBalancesIsMutable();
        balances_.add(index, value);
        onChanged();
      } else {
        balancesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder addBalances(
        io.github.cryptoofun.genproto.BalanceItem.Builder builderForValue) {
      if (balancesBuilder_ == null) {
        ensureBalancesIsMutable();
        balances_.add(builderForValue.build());
        onChanged();
      } else {
        balancesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder addBalances(
        int index, io.github.cryptoofun.genproto.BalanceItem.Builder builderForValue) {
      if (balancesBuilder_ == null) {
        ensureBalancesIsMutable();
        balances_.add(index, builderForValue.build());
        onChanged();
      } else {
        balancesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder addAllBalances(
        java.lang.Iterable<? extends io.github.cryptoofun.genproto.BalanceItem> values) {
      if (balancesBuilder_ == null) {
        ensureBalancesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, balances_);
        onChanged();
      } else {
        balancesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder clearBalances() {
      if (balancesBuilder_ == null) {
        balances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        balancesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public Builder removeBalances(int index) {
      if (balancesBuilder_ == null) {
        ensureBalancesIsMutable();
        balances_.remove(index);
        onChanged();
      } else {
        balancesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public io.github.cryptoofun.genproto.BalanceItem.Builder getBalancesBuilder(
        int index) {
      return getBalancesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public io.github.cryptoofun.genproto.BalanceItemOrBuilder getBalancesOrBuilder(
        int index) {
      if (balancesBuilder_ == null) {
        return balances_.get(index);  } else {
        return balancesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public java.util.List<? extends io.github.cryptoofun.genproto.BalanceItemOrBuilder> 
         getBalancesOrBuilderList() {
      if (balancesBuilder_ != null) {
        return balancesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(balances_);
      }
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public io.github.cryptoofun.genproto.BalanceItem.Builder addBalancesBuilder() {
      return getBalancesFieldBuilder().addBuilder(
          io.github.cryptoofun.genproto.BalanceItem.getDefaultInstance());
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public io.github.cryptoofun.genproto.BalanceItem.Builder addBalancesBuilder(
        int index) {
      return getBalancesFieldBuilder().addBuilder(
          index, io.github.cryptoofun.genproto.BalanceItem.getDefaultInstance());
    }
    /**
     * <code>repeated .BalanceItem balances = 1 [json_name = "balances"];</code>
     */
    public java.util.List<io.github.cryptoofun.genproto.BalanceItem.Builder> 
         getBalancesBuilderList() {
      return getBalancesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.cryptoofun.genproto.BalanceItem, io.github.cryptoofun.genproto.BalanceItem.Builder, io.github.cryptoofun.genproto.BalanceItemOrBuilder> 
        getBalancesFieldBuilder() {
      if (balancesBuilder_ == null) {
        balancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.github.cryptoofun.genproto.BalanceItem, io.github.cryptoofun.genproto.BalanceItem.Builder, io.github.cryptoofun.genproto.BalanceItemOrBuilder>(
                balances_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        balances_ = null;
      }
      return balancesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AskCashBalancesByOffsetAndLimitResponse)
  }

  // @@protoc_insertion_point(class_scope:AskCashBalancesByOffsetAndLimitResponse)
  private static final io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse();
  }

  public static io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AskCashBalancesByOffsetAndLimitResponse>
      PARSER = new com.google.protobuf.AbstractParser<AskCashBalancesByOffsetAndLimitResponse>() {
    @java.lang.Override
    public AskCashBalancesByOffsetAndLimitResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AskCashBalancesByOffsetAndLimitResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AskCashBalancesByOffsetAndLimitResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.cryptoofun.genproto.AskCashBalancesByOffsetAndLimitResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

