// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.github.cryptoofun.genproto;

public interface AskPortfolioResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskPortfolioResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PortfolioItem portfolio = 1 [json_name = "portfolio"];</code>
   */
  java.util.List<io.github.cryptoofun.genproto.PortfolioItem> 
      getPortfolioList();
  /**
   * <code>repeated .PortfolioItem portfolio = 1 [json_name = "portfolio"];</code>
   */
  io.github.cryptoofun.genproto.PortfolioItem getPortfolio(int index);
  /**
   * <code>repeated .PortfolioItem portfolio = 1 [json_name = "portfolio"];</code>
   */
  int getPortfolioCount();
  /**
   * <code>repeated .PortfolioItem portfolio = 1 [json_name = "portfolio"];</code>
   */
  java.util.List<? extends io.github.cryptoofun.genproto.PortfolioItemOrBuilder> 
      getPortfolioOrBuilderList();
  /**
   * <code>repeated .PortfolioItem portfolio = 1 [json_name = "portfolio"];</code>
   */
  io.github.cryptoofun.genproto.PortfolioItemOrBuilder getPortfolioOrBuilder(
      int index);
}
