// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cash_wallet.proto

package io.github.cryptoofun.genproto;

public interface AskTopBalancesDescendingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskTopBalancesDescendingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 skip = 1 [json_name = "skip"];</code>
   * @return The skip.
   */
  int getSkip();

  /**
   * <code>uint32 take = 2 [json_name = "take"];</code>
   * @return The take.
   */
  int getTake();
}
