// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cash_wallet.proto

package io.github.cryptoofun.genproto;

/**
 * Protobuf type {@code AskTopBalancesDescendingRequest}
 */
public final class AskTopBalancesDescendingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AskTopBalancesDescendingRequest)
    AskTopBalancesDescendingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AskTopBalancesDescendingRequest.newBuilder() to construct.
  private AskTopBalancesDescendingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AskTopBalancesDescendingRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AskTopBalancesDescendingRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.cryptoofun.genproto.CashWallet.internal_static_AskTopBalancesDescendingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.cryptoofun.genproto.CashWallet.internal_static_AskTopBalancesDescendingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest.class, io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest.Builder.class);
  }

  public static final int SKIP_FIELD_NUMBER = 1;
  private int skip_ = 0;
  /**
   * <code>uint32 skip = 1 [json_name = "skip"];</code>
   * @return The skip.
   */
  @java.lang.Override
  public int getSkip() {
    return skip_;
  }

  public static final int TAKE_FIELD_NUMBER = 2;
  private int take_ = 0;
  /**
   * <code>uint32 take = 2 [json_name = "take"];</code>
   * @return The take.
   */
  @java.lang.Override
  public int getTake() {
    return take_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (skip_ != 0) {
      output.writeUInt32(1, skip_);
    }
    if (take_ != 0) {
      output.writeUInt32(2, take_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (skip_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, skip_);
    }
    if (take_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, take_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest)) {
      return super.equals(obj);
    }
    io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest other = (io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest) obj;

    if (getSkip()
        != other.getSkip()) return false;
    if (getTake()
        != other.getTake()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKIP_FIELD_NUMBER;
    hash = (53 * hash) + getSkip();
    hash = (37 * hash) + TAKE_FIELD_NUMBER;
    hash = (53 * hash) + getTake();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AskTopBalancesDescendingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AskTopBalancesDescendingRequest)
      io.github.cryptoofun.genproto.AskTopBalancesDescendingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.cryptoofun.genproto.CashWallet.internal_static_AskTopBalancesDescendingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.cryptoofun.genproto.CashWallet.internal_static_AskTopBalancesDescendingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest.class, io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest.Builder.class);
    }

    // Construct using io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      skip_ = 0;
      take_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.cryptoofun.genproto.CashWallet.internal_static_AskTopBalancesDescendingRequest_descriptor;
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest getDefaultInstanceForType() {
      return io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest build() {
      io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest buildPartial() {
      io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest result = new io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.skip_ = skip_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.take_ = take_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest) {
        return mergeFrom((io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest other) {
      if (other == io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest.getDefaultInstance()) return this;
      if (other.getSkip() != 0) {
        setSkip(other.getSkip());
      }
      if (other.getTake() != 0) {
        setTake(other.getTake());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              skip_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              take_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int skip_ ;
    /**
     * <code>uint32 skip = 1 [json_name = "skip"];</code>
     * @return The skip.
     */
    @java.lang.Override
    public int getSkip() {
      return skip_;
    }
    /**
     * <code>uint32 skip = 1 [json_name = "skip"];</code>
     * @param value The skip to set.
     * @return This builder for chaining.
     */
    public Builder setSkip(int value) {

      skip_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 skip = 1 [json_name = "skip"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSkip() {
      bitField0_ = (bitField0_ & ~0x00000001);
      skip_ = 0;
      onChanged();
      return this;
    }

    private int take_ ;
    /**
     * <code>uint32 take = 2 [json_name = "take"];</code>
     * @return The take.
     */
    @java.lang.Override
    public int getTake() {
      return take_;
    }
    /**
     * <code>uint32 take = 2 [json_name = "take"];</code>
     * @param value The take to set.
     * @return This builder for chaining.
     */
    public Builder setTake(int value) {

      take_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 take = 2 [json_name = "take"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTake() {
      bitField0_ = (bitField0_ & ~0x00000002);
      take_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AskTopBalancesDescendingRequest)
  }

  // @@protoc_insertion_point(class_scope:AskTopBalancesDescendingRequest)
  private static final io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest();
  }

  public static io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AskTopBalancesDescendingRequest>
      PARSER = new com.google.protobuf.AbstractParser<AskTopBalancesDescendingRequest>() {
    @java.lang.Override
    public AskTopBalancesDescendingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AskTopBalancesDescendingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AskTopBalancesDescendingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.cryptoofun.genproto.AskTopBalancesDescendingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

