// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cash_wallet.proto

package io.github.cryptoofun.genproto;

public final class CashWallet {
  private CashWallet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskCashBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskCashBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskCashBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskCashBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModifyCashBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModifyCashBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModifyCashBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModifyCashBalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021cash_wallet.proto\"0\n\025AskCashBalanceReq" +
      "uest\022\027\n\007user_id\030\001 \001(\tR\006userId\"K\n\026AskCash" +
      "BalanceResponse\022\027\n\007user_id\030\001 \001(\tR\006userId" +
      "\022\030\n\007balance\030\002 \001(\001R\007balance\"I\n\030ModifyCash" +
      "BalanceRequest\022\027\n\007user_id\030\001 \001(\tR\006userId\022" +
      "\024\n\005delta\030\002 \001(\001R\005delta\"Y\n\031ModifyCashBalan" +
      "ceResponse\022\027\n\007user_id\030\001 \001(\tR\006userId\022#\n\rb" +
      "alance_after\030\002 \001(\001R\014balanceAfter2\246\001\n\021Cas" +
      "hWalletService\022C\n\016AskCashBalance\022\026.AskCa" +
      "shBalanceRequest\032\027.AskCashBalanceRespons" +
      "e\"\000\022L\n\021ModifyCashBalance\022\031.ModifyCashBal" +
      "anceRequest\032\032.ModifyCashBalanceResponse\"" +
      "\000B!\n\035io.github.cryptoofun.genprotoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AskCashBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AskCashBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskCashBalanceRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_AskCashBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AskCashBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskCashBalanceResponse_descriptor,
        new java.lang.String[] { "UserId", "Balance", });
    internal_static_ModifyCashBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ModifyCashBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModifyCashBalanceRequest_descriptor,
        new java.lang.String[] { "UserId", "Delta", });
    internal_static_ModifyCashBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ModifyCashBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModifyCashBalanceResponse_descriptor,
        new java.lang.String[] { "UserId", "BalanceAfter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
