// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package io.github.cryptoofun.genproto;

public interface GetProfileInfoByUserIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetProfileInfoByUserIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  java.util.List<io.github.cryptoofun.genproto.ProfileInfo> 
      getProfileInfoList();
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  io.github.cryptoofun.genproto.ProfileInfo getProfileInfo(int index);
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  int getProfileInfoCount();
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  java.util.List<? extends io.github.cryptoofun.genproto.ProfileInfoOrBuilder> 
      getProfileInfoOrBuilderList();
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  io.github.cryptoofun.genproto.ProfileInfoOrBuilder getProfileInfoOrBuilder(
      int index);
}
