// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package io.github.cryptoofun.genproto;

/**
 * Protobuf type {@code GetProfileInfoByUserIdsResponse}
 */
public final class GetProfileInfoByUserIdsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetProfileInfoByUserIdsResponse)
    GetProfileInfoByUserIdsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetProfileInfoByUserIdsResponse.newBuilder() to construct.
  private GetProfileInfoByUserIdsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetProfileInfoByUserIdsResponse() {
    profileInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetProfileInfoByUserIdsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.cryptoofun.genproto.Profile.internal_static_GetProfileInfoByUserIdsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.cryptoofun.genproto.Profile.internal_static_GetProfileInfoByUserIdsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse.class, io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse.Builder.class);
  }

  public static final int PROFILE_INFO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.github.cryptoofun.genproto.ProfileInfo> profileInfo_;
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  @java.lang.Override
  public java.util.List<io.github.cryptoofun.genproto.ProfileInfo> getProfileInfoList() {
    return profileInfo_;
  }
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.cryptoofun.genproto.ProfileInfoOrBuilder> 
      getProfileInfoOrBuilderList() {
    return profileInfo_;
  }
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  @java.lang.Override
  public int getProfileInfoCount() {
    return profileInfo_.size();
  }
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  @java.lang.Override
  public io.github.cryptoofun.genproto.ProfileInfo getProfileInfo(int index) {
    return profileInfo_.get(index);
  }
  /**
   * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
   */
  @java.lang.Override
  public io.github.cryptoofun.genproto.ProfileInfoOrBuilder getProfileInfoOrBuilder(
      int index) {
    return profileInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < profileInfo_.size(); i++) {
      output.writeMessage(1, profileInfo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < profileInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, profileInfo_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse)) {
      return super.equals(obj);
    }
    io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse other = (io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse) obj;

    if (!getProfileInfoList()
        .equals(other.getProfileInfoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProfileInfoCount() > 0) {
      hash = (37 * hash) + PROFILE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getProfileInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetProfileInfoByUserIdsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetProfileInfoByUserIdsResponse)
      io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.cryptoofun.genproto.Profile.internal_static_GetProfileInfoByUserIdsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.cryptoofun.genproto.Profile.internal_static_GetProfileInfoByUserIdsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse.class, io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse.Builder.class);
    }

    // Construct using io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (profileInfoBuilder_ == null) {
        profileInfo_ = java.util.Collections.emptyList();
      } else {
        profileInfo_ = null;
        profileInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.cryptoofun.genproto.Profile.internal_static_GetProfileInfoByUserIdsResponse_descriptor;
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse getDefaultInstanceForType() {
      return io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse build() {
      io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse buildPartial() {
      io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse result = new io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse result) {
      if (profileInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          profileInfo_ = java.util.Collections.unmodifiableList(profileInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.profileInfo_ = profileInfo_;
      } else {
        result.profileInfo_ = profileInfoBuilder_.build();
      }
    }

    private void buildPartial0(io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse) {
        return mergeFrom((io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse other) {
      if (other == io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse.getDefaultInstance()) return this;
      if (profileInfoBuilder_ == null) {
        if (!other.profileInfo_.isEmpty()) {
          if (profileInfo_.isEmpty()) {
            profileInfo_ = other.profileInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProfileInfoIsMutable();
            profileInfo_.addAll(other.profileInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.profileInfo_.isEmpty()) {
          if (profileInfoBuilder_.isEmpty()) {
            profileInfoBuilder_.dispose();
            profileInfoBuilder_ = null;
            profileInfo_ = other.profileInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            profileInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProfileInfoFieldBuilder() : null;
          } else {
            profileInfoBuilder_.addAllMessages(other.profileInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.cryptoofun.genproto.ProfileInfo m =
                  input.readMessage(
                      io.github.cryptoofun.genproto.ProfileInfo.parser(),
                      extensionRegistry);
              if (profileInfoBuilder_ == null) {
                ensureProfileInfoIsMutable();
                profileInfo_.add(m);
              } else {
                profileInfoBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.cryptoofun.genproto.ProfileInfo> profileInfo_ =
      java.util.Collections.emptyList();
    private void ensureProfileInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        profileInfo_ = new java.util.ArrayList<io.github.cryptoofun.genproto.ProfileInfo>(profileInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.cryptoofun.genproto.ProfileInfo, io.github.cryptoofun.genproto.ProfileInfo.Builder, io.github.cryptoofun.genproto.ProfileInfoOrBuilder> profileInfoBuilder_;

    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public java.util.List<io.github.cryptoofun.genproto.ProfileInfo> getProfileInfoList() {
      if (profileInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(profileInfo_);
      } else {
        return profileInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public int getProfileInfoCount() {
      if (profileInfoBuilder_ == null) {
        return profileInfo_.size();
      } else {
        return profileInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public io.github.cryptoofun.genproto.ProfileInfo getProfileInfo(int index) {
      if (profileInfoBuilder_ == null) {
        return profileInfo_.get(index);
      } else {
        return profileInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder setProfileInfo(
        int index, io.github.cryptoofun.genproto.ProfileInfo value) {
      if (profileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfileInfoIsMutable();
        profileInfo_.set(index, value);
        onChanged();
      } else {
        profileInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder setProfileInfo(
        int index, io.github.cryptoofun.genproto.ProfileInfo.Builder builderForValue) {
      if (profileInfoBuilder_ == null) {
        ensureProfileInfoIsMutable();
        profileInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        profileInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder addProfileInfo(io.github.cryptoofun.genproto.ProfileInfo value) {
      if (profileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfileInfoIsMutable();
        profileInfo_.add(value);
        onChanged();
      } else {
        profileInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder addProfileInfo(
        int index, io.github.cryptoofun.genproto.ProfileInfo value) {
      if (profileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfileInfoIsMutable();
        profileInfo_.add(index, value);
        onChanged();
      } else {
        profileInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder addProfileInfo(
        io.github.cryptoofun.genproto.ProfileInfo.Builder builderForValue) {
      if (profileInfoBuilder_ == null) {
        ensureProfileInfoIsMutable();
        profileInfo_.add(builderForValue.build());
        onChanged();
      } else {
        profileInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder addProfileInfo(
        int index, io.github.cryptoofun.genproto.ProfileInfo.Builder builderForValue) {
      if (profileInfoBuilder_ == null) {
        ensureProfileInfoIsMutable();
        profileInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        profileInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder addAllProfileInfo(
        java.lang.Iterable<? extends io.github.cryptoofun.genproto.ProfileInfo> values) {
      if (profileInfoBuilder_ == null) {
        ensureProfileInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, profileInfo_);
        onChanged();
      } else {
        profileInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder clearProfileInfo() {
      if (profileInfoBuilder_ == null) {
        profileInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        profileInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public Builder removeProfileInfo(int index) {
      if (profileInfoBuilder_ == null) {
        ensureProfileInfoIsMutable();
        profileInfo_.remove(index);
        onChanged();
      } else {
        profileInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public io.github.cryptoofun.genproto.ProfileInfo.Builder getProfileInfoBuilder(
        int index) {
      return getProfileInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public io.github.cryptoofun.genproto.ProfileInfoOrBuilder getProfileInfoOrBuilder(
        int index) {
      if (profileInfoBuilder_ == null) {
        return profileInfo_.get(index);  } else {
        return profileInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public java.util.List<? extends io.github.cryptoofun.genproto.ProfileInfoOrBuilder> 
         getProfileInfoOrBuilderList() {
      if (profileInfoBuilder_ != null) {
        return profileInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(profileInfo_);
      }
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public io.github.cryptoofun.genproto.ProfileInfo.Builder addProfileInfoBuilder() {
      return getProfileInfoFieldBuilder().addBuilder(
          io.github.cryptoofun.genproto.ProfileInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public io.github.cryptoofun.genproto.ProfileInfo.Builder addProfileInfoBuilder(
        int index) {
      return getProfileInfoFieldBuilder().addBuilder(
          index, io.github.cryptoofun.genproto.ProfileInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .ProfileInfo profile_info = 1 [json_name = "profileInfo"];</code>
     */
    public java.util.List<io.github.cryptoofun.genproto.ProfileInfo.Builder> 
         getProfileInfoBuilderList() {
      return getProfileInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.cryptoofun.genproto.ProfileInfo, io.github.cryptoofun.genproto.ProfileInfo.Builder, io.github.cryptoofun.genproto.ProfileInfoOrBuilder> 
        getProfileInfoFieldBuilder() {
      if (profileInfoBuilder_ == null) {
        profileInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.github.cryptoofun.genproto.ProfileInfo, io.github.cryptoofun.genproto.ProfileInfo.Builder, io.github.cryptoofun.genproto.ProfileInfoOrBuilder>(
                profileInfo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        profileInfo_ = null;
      }
      return profileInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetProfileInfoByUserIdsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetProfileInfoByUserIdsResponse)
  private static final io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse();
  }

  public static io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetProfileInfoByUserIdsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetProfileInfoByUserIdsResponse>() {
    @java.lang.Override
    public GetProfileInfoByUserIdsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetProfileInfoByUserIdsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetProfileInfoByUserIdsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.cryptoofun.genproto.GetProfileInfoByUserIdsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

