// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package io.github.cryptoofun.genproto;

public interface GetProfileInfoByUserIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetProfileInfoByUserIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string user_ids = 1 [json_name = "userIds"];</code>
   * @return A list containing the userIds.
   */
  java.util.List<java.lang.String>
      getUserIdsList();
  /**
   * <code>repeated string user_ids = 1 [json_name = "userIds"];</code>
   * @return The count of userIds.
   */
  int getUserIdsCount();
  /**
   * <code>repeated string user_ids = 1 [json_name = "userIds"];</code>
   * @param index The index of the element to return.
   * @return The userIds at the given index.
   */
  java.lang.String getUserIds(int index);
  /**
   * <code>repeated string user_ids = 1 [json_name = "userIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the userIds at the given index.
   */
  com.google.protobuf.ByteString
      getUserIdsBytes(int index);
}
