// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.github.cryptoofun.genproto;

public interface GreetingMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GreetingMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string body = 1 [json_name = "body"];</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 1 [json_name = "body"];</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
