// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package io.github.cryptoofun.genproto;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GreetingMsg message = 1 [json_name = "message"];</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.GreetingMsg message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  io.github.cryptoofun.genproto.GreetingMsg getMessage();
  /**
   * <code>.GreetingMsg message = 1 [json_name = "message"];</code>
   */
  io.github.cryptoofun.genproto.GreetingMsgOrBuilder getMessageOrBuilder();
}
