// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.github.cryptoofun.genproto;

public interface ModifySingleTickerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModifySingleTickerResponse)
    com.google.protobuf.MessageOrBuilder {
}
