// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cash_wallet.proto

package io.github.cryptoofun.genproto;

public interface ModifyCashBalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModifyCashBalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double delta = 1 [json_name = "delta"];</code>
   * @return The delta.
   */
  double getDelta();
}
