// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cash_wallet.proto

package io.github.cryptoofun.genproto;

public interface ModifyCashBalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModifyCashBalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>double balance_after = 2 [json_name = "balanceAfter"];</code>
   * @return The balanceAfter.
   */
  double getBalanceAfter();
}
