// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package io.github.cryptoofun.genproto;

public final class Profile {
  private Profile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetProfileInfoByUserIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetProfileInfoByUserIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProfileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProfileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetProfileInfoByUserIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetProfileInfoByUserIdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprofile.proto\";\n\036GetProfileInfoByUserI" +
      "dsRequest\022\031\n\010user_ids\030\001 \003(\tR\007userIds\"B\n\013" +
      "ProfileInfo\022\027\n\007user_id\030\001 \001(\tR\006userId\022\032\n\010" +
      "username\030\002 \001(\tR\010username\"R\n\037GetProfileIn" +
      "foByUserIdsResponse\022/\n\014profile_info\030\001 \003(" +
      "\0132\014.ProfileInfoR\013profileInfo2p\n\016ProfileS" +
      "ervice\022^\n\027GetProfileInfoByUserIds\022\037.GetP" +
      "rofileInfoByUserIdsRequest\032 .GetProfileI" +
      "nfoByUserIdsResponse\"\000B!\n\035io.github.cryp" +
      "toofun.genprotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetProfileInfoByUserIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetProfileInfoByUserIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetProfileInfoByUserIdsRequest_descriptor,
        new java.lang.String[] { "UserIds", });
    internal_static_ProfileInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProfileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProfileInfo_descriptor,
        new java.lang.String[] { "UserId", "Username", });
    internal_static_GetProfileInfoByUserIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetProfileInfoByUserIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetProfileInfoByUserIdsResponse_descriptor,
        new java.lang.String[] { "ProfileInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
