server:
  port: 7000

grpc:
  server:
    port: 9090 # type -1 to disable
  client:
    hello-server:
      address: 'static://0.0.0.0:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:19092
