[tool.poetry]
name = "load-testing"
version = "1.0.0"
description = ""
authors = []
packages = [{ include = "load_testing" }]

[tool.poetry.dependencies]
python = "^3.7"
locust = "^2.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
