package io.github.cryptoofun.marketdatastreamer;

import java.util.ArrayList;
import java.util.List;

public class AllowedPairs {

    public static final ArrayList<String> populars = new ArrayList<>(
            List.of("BTC_USDT",
                    "BNB_USDT",
                    "ETH_USDT",
                    "XRP_USDT",
                    "DOGE_USDT",
                    "ADA_USDT",
                    "MATIC_USDT",
                    "SOL_USDT")
    );
    public static final ArrayList<String> data = new ArrayList<>(
            List.of("BAT_USDT",
                    "ZIL_USDT",
                    "WAVES_USDT",
                    "VET_USDT",
                    "UNI_USDT",
                    "TRX_USDT",
                    "THETA_USDT",
                    "TFUEL_USDT",
                    "SAND_USDT",
                    "GRT_USDT",
                    "SUSHI_USDT",
                    "XLM_USDT",
                    "SOL_USDT",
                    "SHIB_USDT",
                    "RVN_USDT",
                    "MATIC_USDT",
                    "DOT_USDT",
                    "CAKE_USDT",
                    "OCEAN_USDT",
                    "NEO_USDT",
                    "NEAR_USDT",
                    "EGLD_USDT",
                    "XMR_USDT",
                    "MASK_USDT",
                    "LTC_USDT",
                    "LDO_USDT",
                    "IOTA_USDT",
                    "ICP_USDT",
                    "HOT_USDT",
                    "HBAR_USDT",
                    "ONE_USDT",
                    "FIL_USDT",
                    "FTM_USDT",
                    "ETH_USDT",
                    "ETC_USDT",
                    "EOS_USDT",
                    "ENJ_USDT",
                    "DOGE_USDT",
                    "MANA_USDT",
                    "ATOM_USDT",
                    "LINK_USDT",
                    "ADA_USDT",
                    "BNB_USDT",
                    "BCH_USDT",
                    "BTC_USDT",
                    "AVAX_USDT",
                    "ARB_USDT",
                    "APT_USDT",
                    "ANKR_USDT",
                    "ALGO_USDT",
                    "AAVE_USDT",
                    "APE_USDT",
                    "XRP_USDT"));
}
