// @generated by protoc-gen-es v1.2.0
// @generated from file cash_wallet.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message AskCashBalanceRequest
 */
export const AskCashBalanceRequest = proto3.makeMessageType(
  "AskCashBalanceRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message AskCashBalanceResponse
 */
export const AskCashBalanceResponse = proto3.makeMessageType(
  "AskCashBalanceResponse",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "balance", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message ModifyCashBalanceRequest
 */
export const ModifyCashBalanceRequest = proto3.makeMessageType(
  "ModifyCashBalanceRequest",
  () => [
    { no: 1, name: "delta", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message ModifyCashBalanceResponse
 */
export const ModifyCashBalanceResponse = proto3.makeMessageType(
  "ModifyCashBalanceResponse",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "balance_before", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "balance_after", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

