// @generated by protoc-gen-es v1.2.0
// @generated from file cash_wallet.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message AskCashBalanceRequest
 */
export declare class AskCashBalanceRequest extends Message<AskCashBalanceRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  constructor(data?: PartialMessage<AskCashBalanceRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "AskCashBalanceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskCashBalanceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskCashBalanceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskCashBalanceRequest;

  static equals(a: AskCashBalanceRequest | PlainMessage<AskCashBalanceRequest> | undefined, b: AskCashBalanceRequest | PlainMessage<AskCashBalanceRequest> | undefined): boolean;
}

/**
 * @generated from message AskCashBalanceResponse
 */
export declare class AskCashBalanceResponse extends Message<AskCashBalanceResponse> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: double balance = 2;
   */
  balance: number;

  constructor(data?: PartialMessage<AskCashBalanceResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "AskCashBalanceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AskCashBalanceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AskCashBalanceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AskCashBalanceResponse;

  static equals(a: AskCashBalanceResponse | PlainMessage<AskCashBalanceResponse> | undefined, b: AskCashBalanceResponse | PlainMessage<AskCashBalanceResponse> | undefined): boolean;
}

/**
 * @generated from message ModifyCashBalanceRequest
 */
export declare class ModifyCashBalanceRequest extends Message<ModifyCashBalanceRequest> {
  /**
   * @generated from field: double delta = 1;
   */
  delta: number;

  constructor(data?: PartialMessage<ModifyCashBalanceRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ModifyCashBalanceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModifyCashBalanceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModifyCashBalanceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModifyCashBalanceRequest;

  static equals(a: ModifyCashBalanceRequest | PlainMessage<ModifyCashBalanceRequest> | undefined, b: ModifyCashBalanceRequest | PlainMessage<ModifyCashBalanceRequest> | undefined): boolean;
}

/**
 * @generated from message ModifyCashBalanceResponse
 */
export declare class ModifyCashBalanceResponse extends Message<ModifyCashBalanceResponse> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: double balance_before = 2;
   */
  balanceBefore: number;

  /**
   * @generated from field: double balance_after = 3;
   */
  balanceAfter: number;

  constructor(data?: PartialMessage<ModifyCashBalanceResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ModifyCashBalanceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModifyCashBalanceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModifyCashBalanceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModifyCashBalanceResponse;

  static equals(a: ModifyCashBalanceResponse | PlainMessage<ModifyCashBalanceResponse> | undefined, b: ModifyCashBalanceResponse | PlainMessage<ModifyCashBalanceResponse> | undefined): boolean;
}

